experiment:
    name: "Baseline_data_no_one_cycle000001"
    base_path: "/data/kb4083/cost_model"

data_generation:
    train_dataset_file: "/data/kb4083/datasets/extended_tags/dataset_expr_batch550000-838143_train.pkl"  # training / validation set
    valid_dataset_file: "/data/kb4083/datasets/extended_tags/dataset_expr_batch550000-838143_val.pkl"
    benchmark_dataset_file: "/data/kb4083/model_release/release_code/result_subsample.json"
    dataset_name:  "dataset_new_data"
    batch_size: 1024
    nb_processes: 200

training: 
    log_file: "logs.txt" # Just the name
    lr: 0.00001
    max_epochs: 500
    training_gpu: "3"
    validation_gpu: "cpu"
    continue_training: False
    model_weights_path: "/data/kb4083/cost_model/weights/best_model_Baseline_b14a.pt"

testing:
    testing_model_weights_path: "/data/kb4083/cost_model/best_model_Baseline_176b.pt" # Model weights to evaluate
    gpu: "cuda:2" # GPU to validate on
    

wandb:
    use_wandb: True
    project: "release_model"
    
model: 
    input_size: 846
    comp_embed_layer_sizes:
        - 600
        - 350
        - 200
        - 180
    drops:
        - 0.050
        - 0.050
        - 0.050
        - 0.050
        - 0.050

defaults:
  - override hydra/job_logging: disabled